### ISSUE TITLE
Bugs/inefficiencies/questions relating to refitting

### ISSUE THREAD

**Issue by fionnbishop** [gammacombo/gammacombo#224]
I found a few bugs/inefficiencies related to refitting. I am happy to address these myself, if someone will confirm if I have interpreted these correctly and that the things I've identified as problems do actually need fixing.

**1. setFitStrategy does nothing**
If a fit fails, a refit is carried out, supposedly with a different RooFit strategy. I think this is really helpful behaviour. However, the strategy set with setFitStrategy (below) is not actually applied to the fit in PDF_Datasets::fit. This could be fixed easily.
https://github.com/gammacombo/gammacombo/blob/7472bbf49c71bee18f13688d9d69c48e5406ad4a/core/src/MethodDatasetsPluginScan.cpp#L1189-L1192

**2. Unecessary refitting after physical range check**
https://github.com/gammacombo/gammacombo/blob/7472bbf49c71bee18f13688d9d69c48e5406ad4a/core/src/MethodDatasetsPluginScan.cpp#L1203-L1221
Here there is a refit after checking for and applying the physical range, even if no refit is required. Would it make sense to use a boolean to decide if a refit is necessary like earlier in the script? This would reduce the runtime slightly.
https://github.com/gammacombo/gammacombo/blob/7472bbf49c71bee18f13688d9d69c48e5406ad4a/core/src/MethodDatasetsPluginScan.cpp#L62

**3. Consistency between fit quality criteria in refit decision and plugin scan**
Toys used to calculate p values have requirements on fit status, covariance quality and EDM:
https://github.com/gammacombo/gammacombo/blob/7472bbf49c71bee18f13688d9d69c48e5406ad4a/core/src/MethodDatasetsPluginScan.cpp#L494
In contrast, when deciding whether to refit, only the fit status is checked in general (and at this point corresponds to the fit status from RooFit, so doesn't even take the EDM into account).
https://github.com/gammacombo/gammacombo/blob/7472bbf49c71bee18f13688d9d69c48e5406ad4a/core/src/MethodDatasetsPluginScan.cpp#L1189
Is there any reason not to make these checks consistent? (i.e. both reject toys and refit if any of the fit status, covariance quality or EDM are unsatisfactory). I think this would reduce failure rates.

**Comment by tmombaecher** [comment]
Hi @fionnbishop, thanks for the pointers!
1.  indeed, I spotted that as well, but never bothered (and then forgot) fixing. This could indeed be useful (although if one fit fails, you rarely can recover with other fit strategies). In any case we should reset the fit strategy to the default one if we did change it at some point
2.  that is an important point (for me currently at least). Any unnecessary fit should be avoided, as it can lead to annoyingly large run times. At least the refit should be inside the loop. With a boolean is even better
3. fitstatus checks and EDM checks are the same check (fit is failed if edm>1e-3, if I recall correctly). I don't know whether the too high likelihood was ever a problem (threshold defined before my time). Thinking about it, I guess we don't necessarily rely on an accurate cov matrix for a proper likelihood estimate, so that could even be relaxed.
I hesitate to make too tight requirements to trigger the refitting, since that can easily end up in unexpectedly long loops. So for that fix I would suggest to try the change in an environment with a relevant fraction of failed fits and see whether it makes a difference and not only artificially increases the run time.

**Comment by tmombaecher** [comment]
I intend to have a look at timing issues myself this week. You can assign me to this if you want. Otherwise assign yourself.
In any case the fixes for this issue should be pushed to a separate branch freshly created from the latest development branch to not mix with the other ongoing developments

**Comment by fionnbishop** [comment]
1. I agree with you that refitting with different strategies doesn't help very much - In my experience, it is able to bring the failure rate down to ~0.8-0.9x the original rate. But if the loops to refit 3 times are there, it is certainly worth doing the fit slightly differently each time.
2. 
3. As far as I can tell, fit status takes the EDM into account when deciding whether to reject toys, but not when deciding whether to refit. This is because fit status is generally only set after refitting, e.g.
https://github.com/gammacombo/gammacombo/blob/7472bbf49c71bee18f13688d9d69c48e5406ad4a/core/src/MethodDatasetsPluginScan.cpp#L1275-L1297
You make a very valid point about not wanting to make long loops which provide a minimal reduction in failures. I'll have a look at this and let you know if I do think it would be helpful.
And I agree that it's worth considering if covariance quality requirements could be relaxed.

**Comment by tmombaecher** [comment]
#225 should fix the mentioned behaviour.
