### ISSUE TITLE
CI build fails

### ISSUE THREAD

**Issue by matthewkenzie** [gammacombo/gammacombo#71]
The CI check is failing with the following error:

The command "docker pull schubertkonstantin/cern_root:v5-34-23" failed and exited with 1 during .

See here:

https://travis-ci.org/gammacombo/gammacombo/builds/120837807

Any ideas?

**Comment by KonstantinSchubert** [comment]
The is because the travis.yml for the development branch is outdated. It references a docker repository that doesn't exist any more. 

We can pull the updated travis.yml from the datasets_dev branch.
Or we can ignore the error and live without continuous integration until the datasets_dev is merged into dev.

**Comment by KonstantinSchubert** [comment]
Pull request https://github.com/gammacombo/gammacombo/pull/81 should fix this.

**Comment by KonstantinSchubert** [comment]
This has been fixed, right? Can I close this?

**Comment by matthewkenzie** [comment]
Yes
